name: GitHub Test CI

on:
  push:
    branches: 
      - test-actions

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Respository variables
      run: echo $GITHUB_REPOSITORY
    - name: Git Branch
      run: echo $GITHUB_REF
    - name: Git SHA
      run: echo $GITHUB_SHA
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Get version number
      run: echo ${{ steps.tag.outputs.result }}
    - name: Simple string operation
      run: echo ${GITHUB_REF:10}         
